### ISSUE TITLE
DPLL(T)

### ISSUE THREAD

**Issue by TonitaN** [theElusiveJoe/smt-on-strings-feat-ips#1]
Нужно реализовать базовый алгоритм DPLL(T), учитывая, что условия уже находятся в конъюнктивной нормальной форме. Единственный момент, который в ТЗ отличается от КНФ-формы --- это возможность определять вложенные `or`-структуры, например: `(or (or (= x y) (= x z)) (not (= z y)))`. На входе DPLL такие структуры должны превращаться в плоские, поскольку `or`-оператор допускает сколько угодно аргументов (от 2 и больше).
Считаем, что DPLL оперирует с идентификаторами (переменными пропозициональной логики). Вызов теории T можно сделать пока заглушкой, всегда возвращающей `sat`. Когда именно вызывать решатель теории --- сами определитесь: можно на каждом decide-этапе, как было в лекции, а можно лениво, на листах обхода.

Помним, что с точки зрения построения бенчмарка нас интересуют как раз SAT-формулы.

**Comment by TonitaN** [comment]
К этой заявке прикрепляйте себя.

**Comment by TonitaN** [comment]
Теперь вместо заглушки-true можно порождать образ модели в LIA и вызывать z3, если ещё есть время на это.

**Comment by TonitaN** [comment]
Всё хорошо, но LIA всё ещё вызывается для формулы целиком. Причём при DFS-обходе эта формула константа. Как раз ваше замечание, что теория вызывается просто на набор литералов (получивших к конкретному моменту ветвления значение) - очень правильное, и каноничное DPLL(T) порождает LIA-модель только с литералами, без клоз.
Кстати, в случае образа модели над строками в LIA - бонусом ещё и все литералы положительные. Конечно, если бы мы не в таком узком языке работали, то это было бы уже не так, и not-операции появились бы в образе.

**Comment by TonitaN** [comment]
Кстати, вызов LIA на клозы ещё и слишком жёсткий unsat будет давать, т.к. мы отсеяли not-предложения. Поэтому LIA должен вызываться только на набор литералов.

**Comment by theElusiveJoe** [comment]
т.е надо переделать: 
1. lia вызывается на формулу и список m
2. все положительные литералы из формулы и m просто проверяются в lia по отдельности
я правильно понимаю? 
@TonitaN

**Comment by TonitaN** [comment]
Из списка m выбираем положительные литералы, собираем их в одну lia-модель и запускаем солвер.

**Comment by theElusiveJoe** [comment]
теперь перед вызовом dpll вызывается проверка формулы в lia: отбираются только те клозы, в которых имеются только положительные литералы, и по ним строится lia-формула.
на каждом ветвлении для каждого положительного литерала из m создается свой ассерт в lia

**Comment by TonitaN** [comment]
Если вызывать LIA и на листьях, и на узлах ветвлений, то не понадобится внешний вызов LIA для всей модели, который делается при вызове метода `check-sat` (манипулирующий клозами). Вообще, в самом DPLL(T) LIA у вас вызывается на наборе литералов и действительно находит противоречия по ветвям, то есть работает корректно. 
Пример теста, где нужно проверять на листьях:
```
(assert (or
    (= y (str.++ "ABABC" (str.replace_all y "BBABAB" y) "BCABB"))
  )
)
(assert (or
    (str.contains (str.replace_all y "BBABAB" y) y)
  )
)
```
(он противоречивый в LIA) не строится нетривиальной модели в литералах, только в клозах. Дело в том, что порождаемые литералы получаются уникальными, и DPLL считает, что их нужно просто распространять, а проверять не надо.  
Варианты "вызывать LIA для клоз / вызывать LIA для литералов" обязательно надо оставить оба, как минимум для тестирования, но вообще в самом DPLL(T) используется только второй вариант, а первый уже вызываться не будет.

Кстати, для тестирования DPLL(LIA) удобно оказалось порождать temp-файлы с уникальным таймстемпом в имени, чтобы проследить за тем, какие получаются модели на каком узле. Но это будет вообще не обязательно, если добавить в dot-файл легенду с расшифровкой пропозициональных переменных и в граф -- информацию о том, что противоречие на ветке было получено в LIA.

**Comment by TonitaN** [comment]
Понятно, в чём дело с моделью в LIA! Дело не в том, что в листьях не вызывается проверка для набора литералов, а дело в том, что надо для обращённых значений вызывать. Т.к. в DPLL же значения отрицаний литералов хранятся.
Замена строчки
```
            self.literals = list(filter(lambda x: not(x.negation), m))
```
на такую же без отрицания всё лечит ))

**Comment by theElusiveJoe** [comment]
Я немного запутался:
1. Меняю строчку self.literals = list(filter(lambda x: not(x.negation), m))
2. оставляю вызов lia перед самим dpll, на ветвлении и на листах
3. в граф добавляю легенду с расшифровкой и пометку, если что-то сломалось в lia

**Comment by theElusiveJoe** [comment]
т.е. при проверке списка m в lia я из списка m беру только литералы с отрицанием, и потом это отрицание убираю.
и для каждого полученного литерала строю ассерт

**Comment by TonitaN** [comment]
Ваше изменение более точно, т.к. больше отражает семантику действия. Теперь всё работает, только вызов lia для клоз перед dpll уже делать не надо - это избыточно. Пишите отчёт и на отдых )
