### ISSUE TITLE
Парсинг

### ISSUE THREAD

**Issue by TonitaN** [theElusiveJoe/smt-on-strings-feat-ips#6]
Обработку ошибок делать пока не надо. Но косметические правки всё-таки придётся внести.

1. Парсер принимает вызовы `replace`-функций только с двумя аргументами, хотя их должно быть три.
2. Пустые строки обваливают парсер. Например, как здесь
```
(assert (= (str.replace_all x "A" "") ""))
```
Пустых строк не должно быть вторым аргументом `str.contains` (т.к. это единица моноида, и она всегда есть в слове). И вторым аргументом `str.replace`-ов (по стандарту smt2). Третьим аргументом `str.replace` пустая строка может быть (тогда такой оператор будет просто стирать все или первую указанные во втором аргументе строки). 
В ТЗ написано, что в конкатенациях их тоже лучше не допускать, по той же причине, что в `str.contains`. А вот аргументом равенства пустая строка может быть (но если вторым аргументом будет конкатенация без `replace`-ов, то такое равенство потом выбросится как тривиальное при очистке модели).
3. Все остальные строки у вас сейчас отбрасываются как незначащие. Всё же хорошо было бы хотя бы выделять, в какой теории описана модель (хотя бы LIA, SLIA и S (т.е. строки без LIA)).

**Comment by theElusiveJoe** [comment]
3. Все остальные строки у вас сейчас отбрасываются как незначащие. Всё же хорошо было бы хотя бы выделять, в какой теории описана модель (хотя бы LIA, SLIA и S (т.е. строки без LIA)).

Это значит, надо, чтобы парсер распознавал строки вида (set-logic ...)? Просто, не совсем понятно, для чего программе знать тип логики, если процесс обработки формулы четко определен, и программа всегда знает, когда с какой логикой работать

**Comment by theElusiveJoe** [comment]
На сколько я понимаю, выводить какие-либо формулы в файлы нужно только:
1. при генерации - для прогонки другими солверами
2. при вызове теории lia
А в остальное время удобнее работать с объектом типа Formula

**Comment by TonitaN** [comment]
Один из возможных способов применения этой информации: если теория SLIA, то проводить вызов LIA в DPLL(T), а если теория -- просто S, то просто вызывать его как чекер логической формулы, т.е. вызывать вместо LIA заглушку, как у вас раньше. После чего проверить, решается ли пример солверами именно в чистой теории строк.

Это дешево по затратам сил, а +1 эксперимент. Но всё равно теперь ждать модуля Ярослава до главной части тестирования.
